#!/bin/bash

#############################################
# Nginx Guardian - Automated IP Blocker
# Analyzes current nginx access log and bans suspicious IPs
#############################################


NGINX_LOG="/var/log/nginx/access.log"
MIN_404_REQUESTS=10
MIN_TOTAL_REQUESTS=50
NGINX_CONF="/etc/nginx/conf.d/blocked_ips.conf"
REPORT_FILE="/var/log/nginx_guardian_report.txt"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}" 
   exit 1
fi

while getopts "l:f:t:c:r:" opt; do
  case $opt in
    l) NGINX_LOG="$OPTARG" ;;
    f) MIN_404_REQUESTS="$OPTARG" ;;
    t) MIN_TOTAL_REQUESTS="$OPTARG" ;;
    c) NGINX_CONF="$OPTARG" ;;
    r) REPORT_FILE="$OPTARG" ;;
    \?) echo "Invalid option -$OPTARG" >&2; exit 1 ;;
  esac
done

echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Nginx Guardian v1.0              ║${NC}"
echo -e "${GREEN}║   Automated IP Blocking System         ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""

if [ ! -f "$NGINX_LOG" ]; then
    echo -e "${RED}Error: Nginx log file not found at $NGINX_LOG${NC}"
    exit 1
fi

echo -e "${YELLOW}Analyzing access log...${NC}"
echo ""

awk -v min_404="$MIN_404_REQUESTS" -v min_total="$MIN_TOTAL_REQUESTS" '
{
    ip = $1
    status = $9
    
    total[ip]++
    
    if (status == "404") {
        errors_404[ip]++
    }
    
    if (status == "403" || status == "401") {
        errors_403[ip]++
    }
}

END {
    # Print suspicious IPs
    for (ip in total) {
        e404 = errors_404[ip] + 0
        e403 = errors_403[ip] + 0
        
        if (e404 >= min_404 || total[ip] >= min_total) {
            print ip, total[ip], e404, e403
        }
    }
}
' "$NGINX_LOG" > /tmp/suspicious_ips.txt

# Count suspicious IPs
banned_count=$(wc -l < /tmp/suspicious_ips.txt)


{
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║           NGINX GUARDIAN - SECURITY REPORT                     ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "Report Generated: $(date)"
    echo "Log File: $NGINX_LOG"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
} > "$REPORT_FILE"


if [ "$banned_count" -gt 0 ]; then
    echo -e "${RED}Found $banned_count suspicious IP addresses${NC}"
    echo ""

    if [ -f "$NGINX_CONF" ]; then
        cp "$NGINX_CONF" "${NGINX_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    fi
    

    {
        echo "# Auto-generated by Nginx Guardian on $(date)"
        echo "# DO NOT EDIT MANUALLY"
        echo ""
    } > "$NGINX_CONF"
    
    # Add header to report
    {
        echo "BLOCKED IP ADDRESSES:"
        echo "═══════════════════════════════════════════════════════════════"
        printf "%-20s %-15s %-15s %-15s\n" "IP ADDRESS" "TOTAL REQ" "404 ERRORS" "403/401"
        echo "───────────────────────────────────────────────────────────────"
    } >> "$REPORT_FILE"

    while read -r ip total e404 e403; do

        echo "deny $ip;" >> "$NGINX_CONF"
        

        echo -e "${YELLOW}Banned:${NC} $ip (Total: $total, 404s: $e404, 403/401: $e403)"
        

        printf "%-20s %-15s %-15s %-15s\n" "$ip" "$total" "$e404" "$e403" >> "$REPORT_FILE"
    done < /tmp/suspicious_ips.txt
    
    echo "" >> "$NGINX_CONF"
    echo "allow all;" >> "$NGINX_CONF"
else
    echo -e "${GREEN}No suspicious IPs detected${NC}"
    echo "" >> "$REPORT_FILE"
    echo "No suspicious IPs detected during this analysis period." >> "$REPORT_FILE"
fi


{
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "SUMMARY:"
    echo "═══════════════════════════════════════════════════════════════"
    echo "Total IPs Banned: $banned_count"
    echo "Configuration File: $NGINX_CONF"
    echo "Next Steps: Reload nginx with 'systemctl reload nginx' or 'nginx -s reload'"
    echo ""
} >> "$REPORT_FILE"


echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}SUMMARY${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo "Total IPs Banned: $banned_count"
echo "Report saved to: $REPORT_FILE"
echo "Configuration saved to: $NGINX_CONF"
echo ""

if [ "$banned_count" -gt 0 ]; then
    echo -e "${YELLOW}To apply changes, reload nginx:${NC}"
    echo "  systemctl reload nginx"
    echo "  OR"
    echo "  nginx -s reload"
    echo ""
    

    read -p "Would you like to reload nginx now? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Reloading nginx..."
        if systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null; then
            echo -e "${GREEN}Nginx reloaded successfully!${NC}"
        else
            echo -e "${RED}Failed to reload nginx. Please reload manually.${NC}"
        fi
    fi
fi


echo ""
echo -e "${YELLOW}Full Report:${NC}"
echo "═══════════════════════════════════════════════════════════════"
cat "$REPORT_FILE"

# Cleanup
rm -f /tmp/suspicious_ips.txt

echo ""
echo -e "${GREEN}Nginx Guardian completed successfully!${NC}"
